// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXsHD565klzwC54Z7NsBZIrQhAoztE-Y4',
    appId: '1:1014557879765:web:b11ab05990dfde825ba15c',
    messagingSenderId: '1014557879765',
    projectId: 'mibanco-fm-1714491098',
    authDomain: 'mibanco-fm-1714491098.firebaseapp.com',
    storageBucket: 'mibanco-fm-1714491098.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnIBocXiQuP3sX4dZiAAbE6LZM4y2O4u0',
    appId: '1:1014557879765:android:e5c129ce74d2f5a55ba15c',
    messagingSenderId: '1014557879765',
    projectId: 'mibanco-fm-1714491098',
    storageBucket: 'mibanco-fm-1714491098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0QnpYSOjec0UyF-x5YWj_9yumytnyaoA',
    appId: '1:1014557879765:ios:1a7c90a14f2fed9e5ba15c',
    messagingSenderId: '1014557879765',
    projectId: 'mibanco-fm-1714491098',
    storageBucket: 'mibanco-fm-1714491098.firebasestorage.app',
    iosBundleId: 'com.finanzamovil.mibanco',
  );
}
